# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{hmachine}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Mark Wunsch"]
  s.date = %q{2010-01-09}
  s.description = %q{A Ruby microformat parser powered by Nokogiri}
  s.email = ["mark@markwunsch.com"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".gitignore",
     "Gemfile",
     "LICENSE",
     "README.md",
     "Rakefile",
     "lib/hmachine.rb",
     "lib/hmachine/microformat.rb",
     "lib/hmachine/microformat/base.rb",
     "lib/hmachine/microformat/hcard.rb",
     "test/fixtures/hcard/commercenet.html",
     "test/fixtures/hcard/geo.html",
     "test/hmachine_test.rb",
     "test/microformat/hcard_test.rb",
     "test/microformat_test.rb",
     "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/mwunsch/hmachine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Ruby microformat parser}
  s.test_files = [
    "test/hmachine_test.rb",
     "test/microformat/hcard_test.rb",
     "test/microformat_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<nokogiri>, [">= 0"])
    else
      s.add_dependency(%q<nokogiri>, [">= 0"])
    end
  else
    s.add_dependency(%q<nokogiri>, [">= 0"])
  end
end

